---
title: "DOT_Local_Aid Dataset"
author: "Laura Geronimo"
date: "2024-08-23"
output: html_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE, message=FALSE, warning=FALSE, include=FALSE}
getwd()
setwd('C:/Users/lgero/Box/Research/NJSG/Tradeoff_Analysis/V4')
#libraries
library(tidyverse)
library(networkD3)
library(dplyr)
library(data.table)
library(stringr)
options(scipen=999)

DOT <- read_csv("./data/DataDownloads/NJ_SandyTransparencyData/State_Agency_Datasets/Sandy_DOT_-_Local_Aid_Master_Data.csv")
```

##part 1
##

```{r echo=FALSE, message=FALSE, warning=FALSE, include=FALSE}
##part 1
### Part 1: Data subset and processing: CPI Adjustments
#subset to Ocean County or Toms River (depending on complexity of your data and ease of processing)
table(is.na(DOT$County))
table(is.na(DOT$Municipality))
DOT_Ocean <- subset(DOT, County=="OCEAN")
DOT_TR <- subset(DOT, Municipality=="TOMS RIVER TOWNSHIP") #NA

DOT_Ocean$Year <- sub(".*(.{4})$", "\\1",DOT_Ocean$`As of Date`)

Rt35_37 <- subset(DOT_Ocean, Route=="35, 37")
head(Rt35_37)
Rt35_37$Location #note that Central Ave, Fielder Ave, 6th Ave, 3rd Ave, 2nd Ave, and 6th Ave are in Ortley Beach. Estimate that approximately 1/2 of these repairs were in Ortley

#CPI Adjust
Rt35_37$Total.Cost.Adj <- Rt35_37$`Total Cost`*1.1

#Estimate for OB 
Rt35_37$OB.Est.FedCostShare.Adj <- Rt35_37$Total.Cost.Adj / 2

#Reparing for export
DOT_LocalAid_OB_FedShareEst_ByYear <- Rt35_37 %>%
  select("Federal Agency",
         "Year",
         "OB.Est.FedCostShare.Adj")

path <- 'C:/Users/lgero/Box/Research/NJSG/Tradeoff_Analysis/V4/data/BaselineData/NJ_SandyTransparencey_produced'
write.csv(DOT_LocalAid_OB_FedShareEst_ByYear, file.path(path, "DOT_LocalAid_OB_FedShareEst_ByYear.csv"), row.names = TRUE)
```
