---
title: "NJST: FEMA Public Assistance Program Overview"
author: "Laura Geronimo"
date: '2024-08-23'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}

getwd()
setwd('C:/Users/lgero/Box/Research/NJSG/Tradeoff_Analysis/V4')

#libraries ####
library(tidyverse)
library(networkD3)
library(dplyr)
library(data.table)
library(stringr)

options(scipen=999)

##Importing Data
PA <- read.csv('./data/DataDownloads/NJ_SandyTransparencyData/State_Agency_Datasets/Sandy_PA_Master_Data.csv')

## Explore####
colSums(is.na(PA))
table(PA$Project)

```

### Part 1: Data subset and processing: CPI Adjustments
```{r, include=FALSE}
#subset to Ocean County or Toms River 
table(is.na(PA$County))
table(is.na(PA$Municipality))
PA_Ocean <- subset(PA, County=="OCEAN")
PA_TR <- subset(PA, Municipality=="TOMS RIVER TOWNSHIP")

#examine missing data
colSums(is.na(PA_Ocean)) 
colSums(is.na(PA_TR))

#extracting year
PA_Ocean$Disbursed.Year <- sub(".*(.{4})$", "\\1", PA_Ocean$Federal.Disbursed.Date)
table(PA_Ocean$Disbursed.Year) #
class(PA_Ocean$Disbursed.Year)
PA_Ocean$Disbursed.Year <- as.numeric(PA_Ocean$Disbursed.Year) #needs to be compatible class for join

#creating dataframe for CPI Adjustments
##adjusting for Inflation####
Disbursed.Year<- c(2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023)
CPI <-c(1.17,1.14,1.12,1.10,1.10,1.09,1.06,1.04,1.02,1.00,0.99,0.92,0.86)
CPI  <- data.frame(Disbursed.Year, CPI)
class(CPI$Disbursed.Year)

#join CPI multipliers to Ocean dataframe by year var
PA_Ocean<-left_join(PA_Ocean, CPI, by="Disbursed.Year", copy=F)
colSums(is.na(PA_Ocean))

##multiply the $ amounts you are using in links by CPI and create new var, append 'adj' to var
PA_Ocean$Federal.Disbursed.Amount.Adj <- PA_Ocean$Federal.Disbursed.Amount * PA_Ocean$CPI
PA_Ocean$Local.Share.Adj <- PA_Ocean$Local.Share * PA_Ocean$CPI

#Spot Check:
QC1<-sum(PA_Ocean$Federal.Disbursed.Amount, na.rm=T)
QC2<-sum(PA_Ocean$Federal.Disbursed.Amount.Adj, na.rm=T) #should be greater than QC1
QC3<-QC2-QC1 #looks like it processed

QC1<-sum(PA_Ocean$Local.Share, na.rm=T)
QC2<-sum(PA_Ocean$Local.Share.Adj, na.rm=T) #should be greater than QC1
QC3<-QC2-QC1 #looks like it processed


```


#Creating a subset for Toms River by Year 
##Federal Cost Share by year
```{r include=FALSE}
PA_TR <- subset(PA_Ocean, Municipality=="TOMS RIVER TOWNSHIP")
PA_TR_FederalShare_ByYear <- PA_TR %>% 
  select(`Project`, Disbursed.Year, `Federal.Disbursed.Amount.Adj`) %>% #Use Adjusted version
  group_by(`Project`, Disbursed.Year) %>% 
  summarise(value=sum(`Federal.Disbursed.Amount.Adj`,na.rm = T))%>% 
  ungroup()

names(PA_TR_FederalShare_ByYear) <- c('Project','Disbursed.Year','Federal.Disbursed.Amount.Adj')
PA_TR_FederalShare_ByYear <- na.omit(PA_TR_FederalShare_ByYear)

path <- 'C:/Users/lgero/Box/Research/NJSG/Tradeoff_Analysis/V4/data/BaselineData/NJ_SandyTransparencey_produced'
write.csv(PA_TR_FederalShare_ByYear, file.path(path, "PA_TR_FederalShare_ByYear.csv"), row.names = TRUE)
```

##Local Cost Share
```{r include=FALSE}
PA_TR <- subset(PA_Ocean, Municipality=="TOMS RIVER TOWNSHIP")
PA_TR_LocalShare_ByYear <- PA_TR %>% 
  select(`Project`, Disbursed.Year, `Local.Share.Adj`) %>% #Use Adjusted version
  group_by(`Project`, Disbursed.Year) %>% 
  summarise(value=sum(`Local.Share.Adj`,na.rm = T))%>% 
  ungroup()

names(PA_TR_LocalShare_ByYear) <- c('Project','Disbursed.Year','Local.Share.Adj')
PA_TR_LocalShare_ByYear <- na.omit(PA_TR_LocalShare_ByYear)


path <- 'C:/Users/lgero/Box/Research/NJSG/Tradeoff_Analysis/V4/data/BaselineData/NJ_SandyTransparencey_produced'
write.csv(PA_TR_LocalShare_ByYear, file.path(path, "PA_TR_LocalShare_ByYear.csv"), row.names = TRUE)
```